specVersion: 1.0.0
name: terra-subql-starter
version: 0.0.1
runner:
  node:
    name: '@subql/node-terra'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  This project can be use as a starting point for developing your Terra based
  SubQuery project
repository: https://github.com/subquery/terra-subql-starter
schema:
  file: ./schema.graphql
network:
  chainId: columbus-5
  endpoint: https://terra-columbus-5.beta.api.onfinality.io
  # dictionary: https://api.subquery.network/sq/subquery/terra-columbus-5-dictionary
  # Optionally provide a mantlemint endpoint to further speed up processing
  mantlemint: "https://mantlemint.terra-columbus-5.beta.api.onfinality.io:1320"
dataSources:
  - kind: terra/Runtime
    startBlock: 6402739
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: terra/EventHandler
          filter:
            type: instantiate_contract
            messageFilter:
              type: /terra.wasm.v1beta1.MsgInstantiateContract
              values:
                sender: terra1y4747xzrmtdq04a20zuernnrduvt65qlctkzar
templates:
  - name: NFTContract
    kind: terra/Runtime
    startBlock: 6402739
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleSendNFT
          kind: terra/MessageHandler
          filter:
            type: /terra.wasm.v1beta1.MsgExecuteContract
            contractCall: send_nft